### ISSUE TITLE
Erroneous Right/Down constant pressing when used with separate controller.

### ISSUE THREAD

**Issue by Sharkeology** [mackieks/MaplePad#21]
I am current using the software of this project as a separate VMU to use with my console, it appears and functions perfectly however it will cause the directional pad Right or Down operations to constantly occur after being pressed on a controller connected to a different port. This can be fixed by pressing the button again, but makes any sort of gameplay incredibly difficult.

**Comment by psxrester** [comment]
you should check your solder points, be careful if you use header pins, this could bend the Arduino and make a wrong connection, use flux for your solder points, don't forget to clean the flux after finishing, some flux can cause a mess if not cleaned properly

**Comment by jamesfxh** [comment]
I have the same issue,D-pad up/Down triggered automatically.but only for standard firmware, Also flash Arcade firmware test it's ok.Why is that?

**Comment by mackieks** [comment]
If you use the standard controller firmware, you need to wire up an analog stick and triggers, and run the calibration routines in the menu. You can't leave the analog inputs floating. If you do, you'll get random erroneous inputs like what you're describing.

Some workarounds: 
- edit and recompile the firmware to hardcode the X and Y axes to 0x80
- wire up some resistor dividers to hold the stick inputs at VCC/2
- use the arcade stick firmware

**Comment by jamesfxh** [comment]
> If you use the standard controller firmware, you need to wire up an analog stick and triggers, and run the calibration routines in the menu. You can't leave the analog inputs floating. If you do, you'll get random erroneous inputs like what you're describing.
> 
> Some workarounds:
> 
>     * edit and recompile the firmware to hardcode the X and Y axes to 0x80
> 
>     * wire up some resistor dividers to hold the stick inputs at VCC/2
> 
>     * use the arcade stick firmware

Thanks bro
Refer to your workaround,Adjusted the stick & triggers inputs voltage,and run the calibration program in the menu.It's working fine now.
![WechatIMG661](https://github.com/user-attachments/assets/c14b22d9-75e7-47a3-92af-26f1151099ca)

**Comment by jamesfxh** [comment]
> If you use the standard controller firmware, you need to wire up an analog stick and triggers, and run the calibration routines in the menu. You can't leave the analog inputs floating. If you do, you'll get random erroneous inputs like what you're describing.
> 
> Some workarounds:
> 
>     * edit and recompile the firmware to hardcode the X and Y axes to 0x80
> 
>     * wire up some resistor dividers to hold the stick inputs at VCC/2
> 
>     * use the arcade stick firmware

Thanks bro
Refer to your workaround,Adjusted the stick & triggers inputs voltage,and run the calibration program in the menu.It's working fine now.
![WechatIMG661](https://github.com/user-attachments/assets/c14b22d9-75e7-47a3-92af-26f1151099ca)
