### ISSUE TITLE
Only works on first controller port

### ISSUE THREAD

**Issue by gamecenterjun** [mackieks/MaplePad#3]
Finally got this working, but I wired one and I found that it only works on the first controller port. 

I tried it on Marvel Vs Capcom 2, which grays out the Vs mode option if there are less than two controllers. The VS Mode option just blinks really fast if I connect a regular controller on the first port and a Maplepad to the second port. If I put MaplePad on the first and the stock controller on the second port, it works fine. Any ideas about what's going on?

**Comment by mackieks** [comment]
MaplePad is mostly for portablizing where only controller 1 is used, but the code handles different port addresses so it should work. I will try to reproduce the failure on my setup. Maybe MVC2 is doing something weird or there's a bug in my subperipheral packets.

Have you made any modifications to the code?

**Comment by mackieks** [comment]
OK, I solved the issue by reworking how the port number is handled in the "Absolute Position" field of the data packets. I tested in MVC2 and the VS menu is working as expected with OEM controller in Port A and MaplePad in Port B. 

Here's the ad-hoc build I'm testing with. Please let me know if you're able to verify the fix on your hardware. Be warned: I'm right in the middle of implementing a bunch of new features, so use it at your own risk. 
[maple_pio.zip](https://github.com/mackieks/MaplePad/files/8617386/maple_pio.zip)

**Comment by gamecenterjun** [comment]
Thank you! Will test this today and report back.

**Comment by gamecenterjun** [comment]
Alright, that worked! I have two MaplePads on and versus mode stays on. It looks like the new version is sending random directional inputs at random times, but I have the board wired to an arcade stick so it could be that some directions are wired to ground. I'll test it more later!

**Comment by mackieks** [comment]
Cool, glad to hear it worked. Just FYI, the software is still very much in development and isn't ready for general use yet. The build I sent is set up to use an analog stick and analog triggers with calibration data stored in the flash memory, among other things. 

Eventually I can work on a version that emulates a real arcade stick (HKT-7300) using a stock Pico, but right now I'm focused on more portablizing-focused things like a settings menu on the VMU, guided calibration for sticks and triggers, etc.

**Comment by gamecenterjun** [comment]
Yeah, it's not really usable at since the stick has random inputs but you figured out how to make it work for 2p! Excellent work! Can't wait for the release! 

I'm building a Dreamcast to arcade cabinet adapter and using these pi pico MaplePad boards for controls. I'm happy to run it in single player for now. Thank you!
