### ISSUE TITLE
Compatibility with "regular" Raspberry Pico

### ISSUE THREAD

**Issue by eduardokenj** [mackieks/MaplePad#7]
The maplepad works with raspberry pico with default 2MB SPI memory? Because i wish build an a "easy" DIY board for my arcade stick.

**Comment by mackieks** [comment]
Hi! Yes, it works on the regular Pico. Look at `maple.h` to see which GPIO pins to connect buttons to.

(Once I fix some more compatibility issues, I'll upload wiring diagrams for making custom controllers/arcade sticks.)
