### ISSUE TITLE
Random disconnection

### ISSUE THREAD

**Issue by eduardokenj** [mackieks/MaplePad#8]
I'm use the release v1.4c-arcade on my raspberry pico. In memory menu on bios look like i connect and quickly disconnect the controller, and in 240p test suite in "Maple Devices" item, when i select the maplepad or another controller, the maplepad "disconnect" when I back to menu.

PS: Thanks to your dedication for this project

**Comment by mackieks** [comment]
Thanks for reporting the problem! I'll debug this next week.

**Comment by Wesk87** [comment]
Tested on my side and found no faults with the build. @eduardokenj you may have noise in the data line. Try shortening the line or shielding it.

**Comment by mackieks** [comment]
Also confirmed working on my end. This sounds like a hardware problem, not an issue with the build. Make sure you've followed the wiring diagram in the hardware folder, and check your Pico for cold solder joints or shorts. A loose controller plug or faulty Dreamcast controller daughterboard could also be at fault.

**Comment by mackieks** [comment]
OK, I did find a minor discrepancy between official HKT-7300 and MaplePad (MaplePad's arcade stick Free Device Status and power consumption weren't right) but nothing in the BIOS, 240P Test Suite, or retail SW cares about those fields. You're welcome to try this updated build though!
[maple_pio.zip](https://github.com/mackieks/MaplePad/files/9795966/maple_pio.zip)

**Comment by eduardokenj** [comment]
Well, the new fw works fine, solved the issue... TKS
