### ISSUE TITLE
I2C OLED can't working and bug on 1.4b pio version

### ISSUE THREAD

**Issue by hpx1984** [mackieks/MaplePad#9]
hi Sir

bug1
test 1.4b pio and found the i2c OLED display can't working , once connect I2C OLED display Dreamcast was disconnect PIO board
the screen on OLED as below
![image](https://user-images.githubusercontent.com/76941051/211158460-0792e893-724c-4e7c-bfed-55260d9fcf6a.png)

bug2
for the VMU, when format or copy some game save file on the VMU's last page (8th page) some times Dreamcast will disconnect the PIO board and need re-plug pio board for fix it

suggestion 
now the FW is 1.4d but can't working on PIO board as my tested , is it possible for keep update PIO version FW?
and is it possible for read VMU file via USB port?

**Comment by mackieks** [comment]
Hi! 

- Bug 1 is a do not fix since it's happening on old firmware. Firmware 1.4d works with the SSD1306 I2C OLED in my testing 
- Bug 2 is a known issue, but rarely happens in my tests. The best advice I can give you is to avoid copying large numbers of files at the same time, and wait a little while (~30s) after formatting/copying files before cycling pages or doing another copy.

You mentioned that 1.4d doesn't work on your hardware. Can you give me some more details? What RP2040 board are you using, and how much flash memory does it have? Are you connecting GPIO22 to GND to select the I2C OLED?

Regarding reading out VMU data over USB: it's currently not possible to do this while the controller is operating because the USB code slows down the Maple Bus code too much. However, you can use [picotool](https://github.com/raspberrypi/picotool) to dump VMUs manually. Here's the process:

- Put RP2040 into programming mode with BOOTSEL button
- Use picotool to dump whichever VMU page you want: `picotool save -r 10020000 10040000 dump1.bin`
![image](https://user-images.githubusercontent.com/49252894/211163335-2463ae14-043e-40be-aa93-1a09b1a620f9.png)
- VMUs start at 0x10020000 and each one is 0x20000 long. So to save page 7, for example, you'd use 
`picotool save -r 100E0000 10100000 dump7.bin`
- Open dump in [VMU Explorer](https://segaretro.org/VMU_Explorer)
![image](https://user-images.githubusercontent.com/49252894/211163284-d4100301-11ad-459c-8d29-5afbde9b49f5.png)

**Comment by hpx1984** [comment]
many thanks your quickly replied 
this is really a great project

my board can working with 1.4b , but 1.4c and 1.4d once plug the board to DC the DC will show controller and vmu icon and then after 0.5s the board may disconnect with DC (no icon show on TV's DC VMU screen)

i use green board(maybe 4M，i'm not sure） and black board(memory PY25Q128 16M) 
the green board seems same as the picture "wiring.png"'s official board
![image](https://user-images.githubusercontent.com/76941051/211178171-3473f130-330d-4d9a-a84b-61d8e97c025c.png)


so also can use picotool for program vmu data into the maple VMU, right?
like this :picotool load dump1.bin 10020000 10040000 

i'm think about if possible for load more pages of VMU like 16 pages?

**Comment by mackieks** [comment]
I just reflashed firmware 1.4d on my test controller and both the standard and arcade versions are working fine. You might have a hardware issue, like power or ground wires that are too thin or too long. Can you share photos of your wiring? 

Yes, you should be able to load VMU data into the flash using picotool. However having more than 8 VMU pages would require changes to the code. I think the current 1600 blocks of space is enough for most use cases, and going to 12 or 16 would severely limit space for storing other data, like sprites/animations for the MaplePad menu.

**Comment by hpx1984** [comment]
Dear Sir

but i'm just change the FW to 1.4b the system all working fine(include 1331 OLED and vmu) ,once change FW to 1.4d then got this problem 

now i test on purple board the I2C OLED can show maplepad logo and hold on this logo, and the DC still loss connect after 0.5s
 
the wires seems not very long, i will test again for short the wires
![image](https://user-images.githubusercontent.com/76941051/211182833-b10eefca-b590-49c2-b106-f9db9724b2c3.png)

plug the board on DC A controller port, just saw the controller and vmu icon 0.5s and then loss the icon
![image](https://user-images.githubusercontent.com/76941051/211182853-6015d9bd-7086-4781-92f8-34e23b78f62b.png)

**Comment by mackieks** [comment]
What revision Dreamcast are you using? Is it a VA0 by chance?

**Comment by hpx1984** [comment]
Dear Sir Mackieks

test again for short the DC controller cable ,can't fix the problem
1.4d can't working, 
1.4b good working
Dreamcast HKT-3010 NTSC J, but i don't know the main board number , the Dreamcast product label hasn't print this information, i can disassemble it later

**Comment by mackieks** [comment]
Ok, no problem. I'll look into this more over the next few days and will keep you posted.

**Comment by mackieks** [comment]
@hpx1984 Found a bug in the code and fixed it. Can you test this uf2 and see if it fixes your problem? 
[maplepad.zip](https://github.com/mackieks/MaplePad/files/10369454/maplepad.zip)

**Comment by hpx1984** [comment]
Dear Sir Mackieks

this version can working now , good fixed sir 
Dreamcast can detected the controller and VMU and i2c OLED also working good 

but still has bug: once change page by used GPIO21 to GND then the controller and vmu loss on Dreamcast VMU page

**Comment by mackieks** [comment]
I can't replicate the controller disconnect when cycling pages. Does it also happen when you cycle pages with Start + D-pad Left or Start + D-pad Right?

**Comment by hpx1984** [comment]
i just test the VMU and OLED without controller function , i think i can use some wires for test cycle pages with start+ D-pad

**Comment by mackieks** [comment]
@hpx1984 Any updates?

If you're still experiencing disconnects when cycling, maybe do a nuke_flash using the .uf2 I linked a few messages up, then reflash MaplePad.

**Comment by hpx1984** [comment]
Dear Sir Mackieks 

used unke_flash then used 1.4d still can't use GPIO21+GND for cycle VMU, 
if use start+D PAD can cycle VMU

**Comment by mackieks** [comment]
Ok, that's a separate issue I'll have to debug later. Since you're able to cycle VMUs with the button combo, I'm going to close this for now.

**Comment by hpx1984** [comment]
Dear Sir Mackieks

now very easy disconnect the VMU once format it and it can not fix by un-plug and re-plug into Dreamcast (use nuking uf2 for fix it) 
i do format it just want to set different Icon for let to easy for know which VMU i use when in the game
now the icon is same on I2C OLED screen (same color and same icon)

so just suggest if can't fix this disconnect bug then please change different VMU Icon in next FW update

**Comment by hpx1984** [comment]
i play game and use this VMU for game save ,the screen is show game name so seems different VMU Icon is not impotent

**Comment by rpf16rj** [comment]
Hi, i have same problem, but with standard controller. In some momments the controller stop work and when i connect, the display turn on with logo maplepad but not work. In 240p suit test, the controller is power on and imediatly disconnect at less a second. 

About the calibration of stick, i don't got the axis X and Y work with real sensitive. I have that calibrate more times to got the sensitive work better, but not perfect. The movement skip the 0 to 125.

Another problem, but i don't think that be a conde problem, but my display in games like crazy taxi where stay changing animation in all time, the picture broken and stay crazy.

**Comment by mackieks** [comment]
I know I sound like a broken record, but display *and* controller issues really does seem like a hardware issue. Can you share photos of your setup and soldering? And have you tried with the firmware from [this comment](https://github.com/mackieks/MaplePad/issues/9#issuecomment-1374924291)? 

The calibration/stick scaling isn't bulletproof, but it's pretty decent. However, it can't compensate for sticks that jitter or jump around (the Alps sticks on my Dualshock 4 do this). I need to rewrite the calibration stuff to fix this, just haven't yet.

**Comment by rpf16rj** [comment]
> I know I sound like a broken record, but display _and_ controller issues really does seem like a hardware issue. Can you share photos of your setup and soldering? And have you tried with the firmware from [this comment](https://github.com/mackieks/MaplePad/issues/9#issuecomment-1374924291)?
> 
> The calibration/stick scaling isn't bulletproof, but it's pretty decent. However, it can't compensate for sticks that jitter or jump around (the Alps sticks on my Dualshock 4 do this). I need to rewrite the calibration stuff to fix this, just haven't yet.

So, i tested the firmware from that you tell me, work fine but this is for arcade, my prototype is a standard joystick. 
But, i used some firmwares from of releases from the 1.3 and this also, and now aparently work whout give old problem.
Note: The both analogic L and R i got calibrate perfectly.

![image](https://user-images.githubusercontent.com/21059398/219883127-ed260ab7-665e-48b8-aca6-f770689a802f.png)
![image](https://user-images.githubusercontent.com/21059398/219883131-a3c94cf3-0efa-4f7c-97c3-d4fe2d792078.png)
![image](https://user-images.githubusercontent.com/21059398/219883136-c64d2a67-640e-45b5-877b-63091ab64e30.png)

**Comment by rpf16rj** [comment]
> > I know I sound like a broken record, but display _and_ controller issues really does seem like a hardware issue. Can you share photos of your setup and soldering? And have you tried with the firmware from [this comment](https://github.com/mackieks/MaplePad/issues/9#issuecomment-1374924291)?
> > The calibration/stick scaling isn't bulletproof, but it's pretty decent. However, it can't compensate for sticks that jitter or jump around (the Alps sticks on my Dualshock 4 do this). I need to rewrite the calibration stuff to fix this, just haven't yet.
> 
> So, i tested the firmware from that you tell me, work fine but this is for arcade, my prototype is a standard joystick. But, i used some firmwares from of releases from the 1.3 and this also, and now aparently work whout give old problem. Note: The both analogic L and R i got calibrate perfectly.
> 
> ![image](https://user-images.githubusercontent.com/21059398/219883127-ed260ab7-665e-48b8-aca6-f770689a802f.png) ![image](https://user-images.githubusercontent.com/21059398/219883131-a3c94cf3-0efa-4f7c-97c3-d4fe2d792078.png) ![image](https://user-images.githubusercontent.com/21059398/219883136-c64d2a67-640e-45b5-877b-63091ab64e30.png)

Hi, i discovery the problem with display. I replace to another display and now working fine. Sorry for get your time. 
This project is amazing, congratulations for this.

**Comment by mackieks** [comment]
Glad you figured it out. I just pushed a new release that includes the patches from that build I linked earlier. Feel free to open a separate issue if you encounter more bugs.
